#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <limits.h>
#include <sys/stat.h>

void fix_directory() {
    char cwd[PATH_MAX];
    getcwd(cwd, PATH_MAX);
    strlcat(cwd, "/../", PATH_MAX);
    chdir(cwd);
    mkdir("include/gen", 0777);
}

void fix_name(char *symbol, const char *inname) {
    const int innamelen = strlen(inname);
    if (innamelen > 255) {
        fprintf(stderr, "filename too long\n");
        exit(EXIT_FAILURE);
    }

    for(int i = 0; i < innamelen; i++) {
        if (inname[i] == '.' || inname[i] == '/') {
            symbol[i] = '_';
        } else {
            symbol[i] = inname[i];
        }
    }
    symbol[innamelen] = '\0';
}

int main(const int argc, char **argv) {
    if (argc != 3) {
        fprintf(stderr, "3 arguments required: input file, output header name, output source name\n");
        exit(EXIT_FAILURE);
    }

    fix_directory();

    char *inname = argv[1];
    char *headername = argv[2];

    FILE *input = fopen(inname, "r");
    if (input == NULL) {
        fprintf(stderr, "file not found: %s\n", inname);
        exit(EXIT_FAILURE);
    }

    char symbol[256];
    fix_name(symbol, inname);

    char realheadername[256] = "include/gen/";
    strlcat(realheadername, headername, 256);

    FILE *output = fopen(realheadername, "w");
    if (output == NULL) {
        fprintf(stderr, "file not opened: %s\n", realheadername);
        exit(EXIT_FAILURE);
    }
    fprintf(output, "// AUTOGENERATED, DO NOT MODIFY\n\n"
    "#ifndef __%1$s__\n"
    "#define __%1$s__\n\n"
    "const unsigned char %1$s[] = {\n\t", symbol);

    int index = 0;
    while(1) {
        unsigned char buffer[256];
        const size_t count = fread(buffer, 1, 256, input);
        if (count == 0) break;
        for(int i = 0; i < count; i++) {
            fprintf(output, "0x%02x, ", buffer[i]);
            index++;
            if (index % 20 == 0) {
                fprintf(output, "\n\t");
            }
        }
    }
    if (index % 20 != 0) {
        fprintf(output, "\n");
    }
    fprintf(output, "};\n\n"
        "const int %1$s_len = sizeof(%1$s);\n\n"
                       "#endif\n", symbol);
    fclose(output);

    fclose(input);

    return EXIT_SUCCESS;
}